In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('Pfizer_1.csv')
df.head()

,Date,Drug_Name,Parameter,1:30:00,2:30:00,3:30:00,4:30:00,5:30:00,6:30:00,7:30:00,8:30:00,9:30:00,10:30:00,11:30:00,12:30:00
0,15-10-2020,diltiazem hydrochloride,Temperature,23.0,22.0,NaN,21.0,21.0,22,23.0,21.0,22.0,20,20.0,21
1,15-10-2020,diltiazem hydrochloride,Pressure,12.0,13.0,NaN,11.0,13.0,14,16.0,16.0,24.0,18,19.0,20
2,15-10-2020,docetaxel injection,Temperature,NaN,17.0,18.0,NaN,17.0,18,NaN,NaN,23.0,23,25.0,25
3,15-10-2020,docetaxel injection,Pressure,NaN,22.0,22.0,NaN,22.0,23,NaN,NaN,27.0,26,29.0,28
4,15-10-2020,ketamine hydrochloride,Temperature,24.0,NaN,NaN,27.0,NaN,26,25.0,24.0,23.0,22,21.0,20

In [3]:
pd.melt(df, id_vars=['Date', 'Parameter', 'Drug_Name'])

           Date    Parameter                Drug_Name  variable  value
0    15-10-2020  Temperature  diltiazem hydrochloride   1:30:00   23.0
1    15-10-2020     Pressure  diltiazem hydrochloride   1:30:00   12.0
2    15-10-2020  Temperature      docetaxel injection   1:30:00    NaN
3    15-10-2020     Pressure      docetaxel injection   1:30:00    NaN
4    15-10-2020  Temperature   ketamine hydrochloride   1:30:00   24.0
..          ...          ...                      ...       ...    ...
211  17-10-2020     Pressure  diltiazem hydrochloride  12:30:00   14.0
212  17-10-2020  Temperature      docetaxel injection  12:30:00   23.0
213  17-10-2020     Pressure      docetaxel injection  12:30:00   28.0
214  17-10-2020  Temperature   ketamine hydrochloride  12:30:00   24.0
215  17-10-2020     Pressure   ketamine hydrochloride  12:30:00   15.0

[216 rows x 5 columns]

In [4]:
data_melt = pd.melt(df,id_vars = ['Date', 'Drug_Name', 'Parameter'],
var_name = "time",
value_name = 'reading')
data_melt

           Date                Drug_Name    Parameter      time  reading
0    15-10-2020  diltiazem hydrochloride  Temperature   1:30:00     23.0
1    15-10-2020  diltiazem hydrochloride     Pressure   1:30:00     12.0
2    15-10-2020      docetaxel injection  Temperature   1:30:00      NaN
3    15-10-2020      docetaxel injection     Pressure   1:30:00      NaN
4    15-10-2020   ketamine hydrochloride  Temperature   1:30:00     24.0
..          ...                      ...          ...       ...      ...
211  17-10-2020  diltiazem hydrochloride     Pressure  12:30:00     14.0
212  17-10-2020      docetaxel injection  Temperature  12:30:00     23.0
213  17-10-2020      docetaxel injection     Pressure  12:30:00     28.0
214  17-10-2020   ketamine hydrochloride  Temperature  12:30:00     24.0
215  17-10-2020   ketamine hydrochloride     Pressure  12:30:00     15.0

[216 rows x 5 columns]